apiVersion: v1
data:
  auth-token: TVpXTG5sMkhtb0tKMzNLeGd4TEw3b1B0RExvR1R4VzF3UTZiZldGZ2hVUT0=
  openai-api-key: c2stcHJvai1CbzJjc3F2WExHSDhEMHVaZTJuWUlualV2QWNHeTJ0Q0VJVl9aLW9HZ3otZVh4eDIzQUx6bE1hT3BNWGtKS2pTX1FWM3VSR2ZDb1QzQmxia0ZKWERYNm5pYmNReE4weEtxSkRCSDdNbTRWZUF0NlVsM0YzY2c1azZoY3ZHNnZFRGpRZVRnbU5MWTZrOTZJSjk3dXVCdDJIdUZSb0E=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: dot-ai-client-a
    meta.helm.sh/release-namespace: client-a
  labels:
    app.kubernetes.io/instance: dot-ai-client-a
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dot-ai
    app.kubernetes.io/version: 1.7.0
    helm.sh/chart: dot-ai-1.7.0
  name: dot-ai-secrets
  namespace: client-a
type: Opaque
